language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-project *
  - mkdir -p deploy
  - mv springboot-project.zip deploy/springboot-project.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: springboot-project-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: skdus531/springboot-project #Github 주소
      branch: main
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-project-deploy
    key: springboot-project.zip
    bundle_type: zip
    application: springboot-project
    deployment_group: springboot-project-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: skdus531/springboot-project
      branch: main

notifications:
  email:
    recipients:
      - skdus531@daum.net